name: mymgs
description: Mobile-native client for the MyMGS database.

# Prevents accidental publication (don't remove this line)
publish_to: 'none'

# Automatically copied into iOS and Android versions at build time.
# Public-facing semver code, followed by a '+', and then the build number (must always be larger than the previous published build)
version: 0.5.0+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase modules
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2
  cloud_functions: ^1.1.2
  firebase_auth: ^1.4.1
  firebase_messaging: ^10.0.2
  firebase_crashlytics: ^2.0.6
  firebase_remote_config: ^0.10.0+2
  firebase_dynamic_links: ^2.0.6
  firebase_analytics: ^8.1.2

  # everything else
  grouped_list: ^4.0.0
  infinite_listview: ^1.1.0
  jiffy: ^4.1.0
  flutter_markdown: ^0.6.2
  flutter_local_notifications: ^6.0.0
  flutter_platform_widgets: ^1.9.5
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2
  uuid: ^3.0.4
  http: ^0.13.3
  uni_links: ^0.5.1
  flutter_web_browser: ^0.14.0
  cached_network_image: ^3.0.0
  sembast: ^3.1.0+2
  protobuf: ^2.0.0
  url_launcher: ^6.0.6
  mask_text_input_formatter: ^2.0.0
  sembast_web: ^2.0.0+2
  collection: ^1.15.0
  share: ^2.0.4
  confetti: ^0.6.0-nullsafety
  google_fonts: ^2.1.0
  qr_code_scanner: ^0.5.1
  qr_flutter: ^4.0.0
  universal_html: ^2.0.8
  flutter_staggered_grid_view: ^0.4.0
  shimmer: ^2.0.0

  openpgp: ^2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  flutter_launcher_icons: ^0.9.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Newsreader
      fonts:
        - asset: fonts/Newsreader-Regular.ttf

  assets:
    - assets/
