name: mymgs
description: Mobile-native client for the MyMGS database.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0-1-school-council+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase modules
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.1
  cloud_functions: ^1.0.0
  firebase_auth: ^1.0.1
  firebase_messaging: ^9.0.0
  firebase_crashlytics: ^1.0.0
  firebase_remote_config: ^0.9.0-dev.1
  firebase_dynamic_links: ^0.8.0

  # everything else
  grouped_list: ^4.0.0-nullsafety.1
  infinite_listview: ^1.0.1+1
  jiffy: ^4.0.0
  flutter_markdown: ^0.6.0
  flutter_local_notifications: ^5.0.0-nullsafety.1
  flutter_platform_widgets: ^1.0.1-nullsafety.0
  json_annotation: ^4.0.0
  shared_preferences: ^2.0.3
  path_provider: ^2.0.1
  uuid: ^3.0.1
  http: ^0.13.0
  uni_links: ^0.4.0
  flutter_web_browser: ^0.13.1
  cached_network_image: ^3.0.0-nullsafety
  sembast: ^3.0.0+4
  protobuf: ^2.0.0
  url_launcher: ^6.0.2
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  sembast_web: ^2.0.0+2
  collection: ^1.15.0
  share: ^2.0.1
  confetti: ^0.6.0-nullsafety

  openpgp: ^2.0.0-nullsafety.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^1.11.5
  json_serializable: ^4.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Newsreader
      fonts:
        - asset: fonts/Newsreader-Regular.ttf
