String getSafeguardingKey() {
  return """-----BEGIN PUBLIC KEY-----
MIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQBn2oO3MO8oZBpMuN5Ia6D6
JiFiv5lCA+P9Wa5MWNSALDZj4M+qDH6l5aKAEqicvQOOlQSBikR31V6AV/tDXtGT
7LrvPFl3/QMCrdTjCL94+UimqxLXHszEXBsGv8zvHMMlfimMFjHjHCBgKieD1tPo
WFCKgpwZ2W+dgOO/Tz95FXIMpkf6MHNoNnzZ4oSn2J20gf31mKl2DDVrBxkoWjDE
Ose98FkTKHp6e0vPnMPw0aexsC+LmUjQwsdP7KOlmWG+NAoxyS3I1kUwPbnndNt/
N2kBHielBBc8S9ZftvsKbYPhu+c+C5urcLLHd4syYEsGFxJxUcRRSKohZkJy/znL
AgMBAAE=
-----END PUBLIC KEY-----""";
}