# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    path = "fastlane/key.json"

    # works for GitHub actions too
    if is_ci
      setup_ci(provider: "travis")
    end
    match(type: "appstore", readonly: is_ci, api_key_path: path)

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Runner.xcodeproj",
      profile_name: ENV["sigh_org.mgs.my.ios_appstore_profile-name"],
      profile_uuid: ENV["sigh_org.mgs.my.ios_appstore"]
    )
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner"
    )
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      api_key_path: path,
      force: true,
      run_precheck_before_submit: false,
      submit_for_review: false,
      automatic_release: false,
    )
  end
end
