# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    path = "fastlane/key.json"

    # works for GitHub actions too
    setup_ci(provider: "travis")
    match(type: "appstore", readonly: true, api_key_path: path)

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner"
    )
    upload_to_app_store(skip_metadata: true, skip_screenshots: true, api_key_path: path)
  end
end
