name: Build for Android

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Compilation mode to use (appbundle or apk)'
        required: true
        default: 'appbundle'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.2'

      - name: Configure Keystore
        run: |
          echo "$ANDROID_STORE_FILE" | base64 --decode > app/temp_key.jks
          echo "storeFile=temp_key.jks" >> key.properties
          echo "keyAlias=$ANDROID_KEY_ALIAS" >> key.properties
          echo "storePassword=$ANDROID_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$ANDROID_KEY_PASSWORD" >> key.properties
        env:
          ANDROID_STORE_FILE: ${{ secrets.ANDROID_STORE_FILE }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
        working-directory: android

      - name: Install dependencies
        run: flutter pub get
      - name: Build Flutter
        run: flutter build ${{ github.event.inputs.mode || 'appbundle' }} --release -v

      - name: Upload Bundle artifact
        if: ${{ github.event.inputs.mode == 'appbundle }}
        uses: actions/upload-artifact@v2
        with:
          name: release-bundle
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload APK artifact
        if: ${{ github.event.inputs.mode == 'apk }}
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
