name: Build for iOS

on:
  workflow_dispatch

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Install Pods
        run: pod install
        working-directory: ios

      - name: Copy key to file
        run: echo "$APIKEY" > "key.json"
        working-directory: ios/fastlane
        env:
          APIKEY: ${{ secrets.FASTLANE_API_KEY }}

      - name: Build, sign, upload using Fastlane
        run: bundle exec fastlane release
        working-directory: ios
        env:
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.FASTLANE_MATCH_GIT_BASIC_AUTHORIZATION }}
