name: Build & Deploy for web

on:
  push:
    branches:
      - main
    paths:
      - lib/*
      - assets/*
      - fonts/*
      - web/*
      - pubspec.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.2'

      - run: flutter pub get
      - run: flutter build web --release -v
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: my-mgs-app
          channelId: live
